name: scrolling-habits

plugins:
  - name: solidity
  - name: foundry

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.2

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/5.0.2"